### ISSUE TITLE
Compatibility with libsodium 0.5.0

### ISSUE THREAD

**Issue by t-koehler** [joshjdevl/libsodium-jni#6]
Is there any chance to get KaliumJNI working with latest stable libsodium 0.5.0? The Error occured after executing "ndk-build" for arm arch on Debian Jessie. The libsodium 0.4.5 is just working fine...

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.380s
[INFO] Finished at: Tue Jun 03 16:35:01 CEST 2014
[INFO] Final Memory: 15M/178M
[INFO] ------------------------------------------------------------------------
[armeabi] Compile thumb  : testjni <= sodium_wrap.c
In file included from /installs/android-ndk-r9c/platforms/android-3/arch-arm/usr/include/linux/stddef.h:21:0,
                 from /installs/android-ndk-r9c/platforms/android-3/arch-arm/usr/include/linux/posix_types.h:15,
                 from /installs/android-ndk-r9c/platforms/android-3/arch-arm/usr/include/sys/types.h:37,
                 from /installs/android-ndk-r9c/platforms/android-3/arch-arm/usr/include/strings.h:42,
                 from /installs/android-ndk-r9c/platforms/android-3/arch-arm/usr/include/stdlib.h:42,
                 from jni/sodium_wrap.c:136:
/installs/android-ndk-r9c/platforms/android-3/arch-arm/usr/include/linux/compiler.h:25:31: warning: ISO C does not permit named variadic macros [-Wvariadic-macros]
jni/sodium_wrap.c: In function 'Java_org_abstractj_kalium_SodiumJNI_crypto_1hash_1sha256_1ref':
jni/sodium_wrap.c:800:3: warning: implicit declaration of function 'crypto_hash_sha256_ref' [-Wimplicit-function-declaration]
jni/sodium_wrap.c: In function 'Java_org_abstractj_kalium_SodiumJNI_crypto_1hash_1sha512_1ref':
jni/sodium_wrap.c:830:3: warning: implicit declaration of function 'crypto_hash_sha512_ref' [-Wimplicit-function-declaration]
jni/sodium_wrap.c: In function 'Java_org_abstractj_kalium_SodiumJNI_crypto_1box_1curve25519xsalsa20poly1305_1ref_1keypair':
jni/sodium_wrap.c:900:3: warning: implicit declaration of function 'crypto_box_curve25519xsalsa20poly1305_ref_keypair' [-Wimplicit-function-declaration]
jni/sodium_wrap.c: In function 'Java_org_abstractj_kalium_SodiumJNI_crypto_1box_1curve25519xsalsa20poly1305_1ref':
jni/sodium_wrap.c:960:3: warning: implicit declaration of function 'crypto_box_curve25519xsalsa20poly1305_ref' [-Wimplicit-function-declaration]
jni/sodium_wrap.c: In function 'Java_org_abstractj_kalium_SodiumJNI_crypto_1box_1curve25519xsalsa20poly1305_1ref_1open':
jni/sodium_wrap.c:1014:3: warning: implicit declaration of function 'crypto_box_curve25519xsalsa20poly1305_ref_open' [-Wimplicit-function-declaration]
jni/sodium_wrap.c: In function 'Java_org_abstractj_kalium_SodiumJNI_crypto_1scalarmult_1curve25519_1ref':
jni/sodium_wrap.c:1058:3: warning: implicit declaration of function 'crypto_scalarmult_curve25519_ref' [-Wimplicit-function-declaration]
jni/sodium_wrap.c: In function 'Java_org_abstractj_kalium_SodiumJNI_crypto_1secretbox_1xsalsa20poly1305_1ref':
jni/sodium_wrap.c:1100:3: warning: implicit declaration of function 'crypto_secretbox_xsalsa20poly1305_ref' [-Wimplicit-function-declaration]
jni/sodium_wrap.c: In function 'Java_org_abstractj_kalium_SodiumJNI_crypto_1secretbox_1xsalsa20poly1305_1ref_1open':
jni/sodium_wrap.c:1146:3: warning: implicit declaration of function 'crypto_secretbox_xsalsa20poly1305_ref_open' [-Wimplicit-function-declaration]
jni/sodium_wrap.c: In function 'Java_org_abstractj_kalium_SodiumJNI_crypto_1sign_1ed25519_1ref_1seed_1keypair':
jni/sodium_wrap.c:1186:3: warning: implicit declaration of function 'crypto_sign_ed25519_ref_seed_keypair' [-Wimplicit-function-declaration]
jni/sodium_wrap.c: In function 'Java_org_abstractj_kalium_SodiumJNI_crypto_1sign_1ed25519_1ref':
jni/sodium_wrap.c:1227:3: warning: implicit declaration of function 'crypto_sign_ed25519_ref' [-Wimplicit-function-declaration]
jni/sodium_wrap.c: In function 'Java_org_abstractj_kalium_SodiumJNI_crypto_1sign_1ed25519_1ref_1open':
jni/sodium_wrap.c:1270:3: warning: implicit declaration of function 'crypto_sign_ed25519_ref_open' [-Wimplicit-function-declaration]
jni/sodium_wrap.c: At top level:
jni/sodium_wrap.c:255:12: warning: 'SWIG_JavaArrayInSchar' defined but not used [-Wunused-function]
jni/sodium_wrap.c:276:13: warning: 'SWIG_JavaArrayArgoutSchar' defined but not used [-Wunused-function]
jni/sodium_wrap.c:284:19: warning: 'SWIG_JavaArrayOutSchar' defined but not used [-Wunused-function]
jni/sodium_wrap.c:301:12: warning: 'SWIG_JavaArrayInUchar' defined but not used [-Wunused-function]
jni/sodium_wrap.c:322:13: warning: 'SWIG_JavaArrayArgoutUchar' defined but not used [-Wunused-function]
jni/sodium_wrap.c:330:20: warning: 'SWIG_JavaArrayOutUchar' defined but not used [-Wunused-function]
jni/sodium_wrap.c:347:12: warning: 'SWIG_JavaArrayInShort' defined but not used [-Wunused-function]
jni/sodium_wrap.c:368:13: warning: 'SWIG_JavaArrayArgoutShort' defined but not used [-Wunused-function]
jni/sodium_wrap.c:376:20: warning: 'SWIG_JavaArrayOutShort' defined but not used [-Wunused-function]
jni/sodium_wrap.c:393:12: warning: 'SWIG_JavaArrayInUshort' defined but not used [-Wunused-function]
jni/sodium_wrap.c:414:13: warning: 'SWIG_JavaArrayArgoutUshort' defined but not used [-Wunused-function]
jni/sodium_wrap.c:422:18: warning: 'SWIG_JavaArrayOutUshort' defined but not used [-Wunused-function]
jni/sodium_wrap.c:439:12: warning: 'SWIG_JavaArrayInInt' defined but not used [-Wunused-function]
jni/sodium_wrap.c:460:13: warning: 'SWIG_JavaArrayArgoutInt' defined but not used [-Wunused-function]
jni/sodium_wrap.c:468:18: warning: 'SWIG_JavaArrayOutInt' defined but not used [-Wunused-function]
jni/sodium_wrap.c:485:12: warning: 'SWIG_JavaArrayInUint' defined but not used [-Wunused-function]
jni/sodium_wrap.c:506:13: warning: 'SWIG_JavaArrayArgoutUint' defined but not used [-Wunused-function]
jni/sodium_wrap.c:514:19: warning: 'SWIG_JavaArrayOutUint' defined but not used [-Wunused-function]
jni/sodium_wrap.c:560:18: warning: 'SWIG_JavaArrayOutLong' defined but not used [-Wunused-function]
jni/sodium_wrap.c:577:12: warning: 'SWIG_JavaArrayInUlong' defined but not used [-Wunused-function]
jni/sodium_wrap.c:598:13: warning: 'SWIG_JavaArrayArgoutUlong' defined but not used [-Wunused-function]
jni/sodium_wrap.c:606:19: warning: 'SWIG_JavaArrayOutUlong' defined but not used [-Wunused-function]
jni/sodium_wrap.c:623:12: warning: 'SWIG_JavaArrayInLonglong' defined but not used [-Wunused-function]
jni/sodium_wrap.c:644:13: warning: 'SWIG_JavaArrayArgoutLonglong' defined but not used [-Wunused-function]
jni/sodium_wrap.c:652:19: warning: 'SWIG_JavaArrayOutLonglong' defined but not used [-Wunused-function]
jni/sodium_wrap.c:669:12: warning: 'SWIG_JavaArrayInFloat' defined but not used [-Wunused-function]
jni/sodium_wrap.c:690:13: warning: 'SWIG_JavaArrayArgoutFloat' defined but not used [-Wunused-function]
jni/sodium_wrap.c:698:20: warning: 'SWIG_JavaArrayOutFloat' defined but not used [-Wunused-function]
jni/sodium_wrap.c:715:12: warning: 'SWIG_JavaArrayInDouble' defined but not used [-Wunused-function]
jni/sodium_wrap.c:736:13: warning: 'SWIG_JavaArrayArgoutDouble' defined but not used [-Wunused-function]
jni/sodium_wrap.c:744:21: warning: 'SWIG_JavaArrayOutDouble' defined but not used [-Wunused-function]
[armeabi] SharedLibrary  : libtestjni.so
/installs/android-ndk-r9c/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: ./obj/local/armeabi/objs/testjni/sodium_wrap.o: in function Java_org_abstractj_kalium_SodiumJNI_crypto_1hash_1sha256_1ref:jni/sodium_wrap.c:800: error: undefined reference to 'crypto_hash_sha256_ref'
/installs/android-ndk-r9c/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: ./obj/local/armeabi/objs/testjni/sodium_wrap.o: in function Java_org_abstractj_kalium_SodiumJNI_crypto_1hash_1sha512_1ref:jni/sodium_wrap.c:830: error: undefined reference to 'crypto_hash_sha512_ref'
/installs/android-ndk-r9c/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: ./obj/local/armeabi/objs/testjni/sodium_wrap.o: in function Java_org_abstractj_kalium_SodiumJNI_crypto_1box_1curve25519xsalsa20poly1305_1ref_1keypair:jni/sodium_wrap.c:900: error: undefined reference to 'crypto_box_curve25519xsalsa20poly1305_ref_keypair'
/installs/android-ndk-r9c/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: ./obj/local/armeabi/objs/testjni/sodium_wrap.o: in function Java_org_abstractj_kalium_SodiumJNI_crypto_1box_1curve25519xsalsa20poly1305_1ref:jni/sodium_wrap.c:960: error: undefined reference to 'crypto_box_curve25519xsalsa20poly1305_ref'
/installs/android-ndk-r9c/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: ./obj/local/armeabi/objs/testjni/sodium_wrap.o: in function Java_org_abstractj_kalium_SodiumJNI_crypto_1box_1curve25519xsalsa20poly1305_1ref_1open:jni/sodium_wrap.c:1014: error: undefined reference to 'crypto_box_curve25519xsalsa20poly1305_ref_open'
/installs/android-ndk-r9c/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: ./obj/local/armeabi/objs/testjni/sodium_wrap.o: in function Java_org_abstractj_kalium_SodiumJNI_crypto_1scalarmult_1curve25519_1ref:jni/sodium_wrap.c:1058: error: undefined reference to 'crypto_scalarmult_curve25519_ref'
/installs/android-ndk-r9c/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: ./obj/local/armeabi/objs/testjni/sodium_wrap.o: in function Java_org_abstractj_kalium_SodiumJNI_crypto_1secretbox_1xsalsa20poly1305_1ref:jni/sodium_wrap.c:1100: error: undefined reference to 'crypto_secretbox_xsalsa20poly1305_ref'
/installs/android-ndk-r9c/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: ./obj/local/armeabi/objs/testjni/sodium_wrap.o: in function Java_org_abstractj_kalium_SodiumJNI_crypto_1secretbox_1xsalsa20poly1305_1ref_1open:jni/sodium_wrap.c:1146: error: undefined reference to 'crypto_secretbox_xsalsa20poly1305_ref_open'
/installs/android-ndk-r9c/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: ./obj/local/armeabi/objs/testjni/sodium_wrap.o: in function Java_org_abstractj_kalium_SodiumJNI_crypto_1sign_1ed25519_1ref_1seed_1keypair:jni/sodium_wrap.c:1186: error: undefined reference to 'crypto_sign_ed25519_ref_seed_keypair'
/installs/android-ndk-r9c/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: ./obj/local/armeabi/objs/testjni/sodium_wrap.o: in function Java_org_abstractj_kalium_SodiumJNI_crypto_1sign_1ed25519_1ref:jni/sodium_wrap.c:1227: error: undefined reference to 'crypto_sign_ed25519_ref'
/installs/android-ndk-r9c/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: ./obj/local/armeabi/objs/testjni/sodium_wrap.o: in function Java_org_abstractj_kalium_SodiumJNI_crypto_1sign_1ed25519_1ref_1open:jni/sodium_wrap.c:1270: error: undefined reference to 'crypto_sign_ed25519_ref_open'
collect2: ld returned 1 exit status
make: *** [obj/local/armeabi/libtestjni.so] Error 1
```
